### ISSUE TITLE
Module subpath doesn't resolve

### ISSUE THREAD

**Issue by lukiffer** [sheerlox/import-from-esm#107]
Ran into an issue when using semantic-release with a shared config (CommonJS) using subpaths.

With a destination package `@example/package/subpath`, assuming the target file in the package `@example/package` exists in `./subpath/index.js`, I get something like the following:

```
import-from-esm Trying to resolve '@example/package/subpath' from 'file:///Users/lukiffer/.npm/_npx/db57d9b03a028fc5/node_modules/semantic-release/lib/noop.js' +0ms
  import-from-esm Failed to resolve '@example/package/subpath' from 'file:///Users/lukiffer/.npm/_npx/db57d9b03a028fc5/node_modules/semantic-release/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@example/package' imported from /Users/lukiffer/.npm/_npx/db57d9b03a028fc5/node_modules/semantic-release/lib/noop.js +0ms
```

If I instead move and rename the target file from `./subpath/index.js` to `./subpath.cjs` this works as expected.

I'm not sure if this is something that `import-from` previously masked or if `./subpath/index.js` should actually be checked, and if so why it's failing to find the root package.

**Comment by sheerlox** [comment]
Hi @lukiffer, sorry you're encountering an issue with this package!

Could you please run the failing command with the `DEBUG=import-from-esm` env variable? This will log every path its tried to resolve.

**Comment by lukiffer** [comment]
Here's the actual output: https://gist.github.com/lukiffer/fd3f0b38960555b7bb808fdb5edc42f7

(I think) the issue is with the first resolve attempt:

```
Trying to resolve '@bdrk/semantic-release-config/npm'
```

In this case, a file does in fact exist at `node_modules/@bdrk/semantic-release-config/npm/index.js` but is throwing `ERR_MODULE_NOT_FOUND`.

Moving the file to `./npm.js` (with `type="commonjs"` in `package.json`) or moving it to `./npm.cjs` both work fine. So it seems like it's either not trying the `index.js` default, or having some trouble locating it.

**Comment by sheerlox** [comment]
Ok, I found the issue. I'm working on a fix and should be releasing that in the next few hours, will keep you updated. Thanks for the heads up!

**Comment by sheerlox** [comment]
Renovate should update the dependency on the various @semantic-release repos in the next few hours!

Feel free to reopen if you're still getting an issue after upgrading :smile:
